#!/usr/bin/env python3
"""
GenTech V4 — Build Queue Tick (skill copy)
Runs autonomously every 30 min via cron (no_agent=True).
Scans build_queue.json, reports status, and generates task-forwarding outputs.

Outputs:
  - stdout summary → captured by cron, available to agent-run jobs via context_from
  - forge-handoff.md → Forge's actionable task list (read by Nightly Build Session)
  - jordan-action-items.md → items needing Jordan's decision

See skill: gentech-ops/build-queue
"""

import json
import os
import sys
from datetime import datetime, timezone

QUEUE_PATH = os.environ.get(
    "BUILD_QUEUE_PATH",
    "/root/vaults/gentech/scripts/build_queue.json"
)
HANDOFF_DIR = os.environ.get(
    "HANDOFF_DIR",
    "/root/vaults/gentech/01-HANDOFFS"
)
AGENT = os.environ.get("AGENT", "gentech")

DIFFICULTY = {"easy": 0, "medium": 1, "hard": 2}
PRIORITY = {"urgent": 0, "high": 1, "medium": 2, "low": 3}


def load_queue():
    """Load the build queue and normalize to a list of items.

    The queue file has historically been either a dict with an "items" key
    ({"version": ..., "items": [...]}) or a bare list of items. Normalize
    both to a plain list so downstream code can always iterate q["items"].
    """
    try:
        with open(QUEUE_PATH) as f:
            raw = json.load(f)
    except FileNotFoundError:
        print(f"ERROR: Queue file not found at {QUEUE_PATH}")
        print("ACTION: Gentech needs to run vault-sync or rebuild the queue.")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"ERROR: Queue file corrupt — {e}")
        sys.exit(1)
    if isinstance(raw, dict):
        # dict form: {"version": ..., "items": [...]}
        return raw
    if isinstance(raw, list):
        # bare-list form: normalize to the dict shape the rest of the script expects
        return {"version": "list", "items": raw}
    print(f"ERROR: Queue file has unexpected top-level type {type(raw).__name__}")
    sys.exit(1)


def find_next_tasks(q, agent, count=3):
    """Find next available tasks for a given agent."""
    available = [
        i for i in q["items"]
        if i["status"] == "pending"
        and i.get("assigned_to") in (agent, "auto")
        and not i.get("needs_jordan", False)
    ]
    available.sort(key=lambda x: (
        DIFFICULTY.get(x.get("difficulty", "medium"), 1),
        PRIORITY.get(x.get("priority", "low"), 99),
        x.get("id", 999)
    ))
    return available[:count]


def generate_forge_handoff(q):
    """Generate a clean task-forwarding handoff markdown for Forge."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    os.makedirs(HANDOFF_DIR, exist_ok=True)
    path = os.path.join(HANDOFF_DIR, f"{today}-forge-tasks.md")

    forge_items = [
        i for i in q["items"]
        if i.get("assigned_to") == "forge" and i["status"] == "pending"
    ]
    either_items = [
        i for i in q["items"]
        if i.get("assigned_to") in ("auto",) and i["status"] == "pending"
        and not i.get("needs_jordan", False)
    ]

    lines = [
        f"# Forge Task List — {today}",
        "",
        "**Auto-generated by Build Queue Tick.**",
        "Items you can work on independently — no Jordan needed.",
        "",
        "---",
        "",
        f"## 🖥️ Desktop — Your Lane ({len(forge_items)} items)",
        "",
    ]
    for i in forge_items:
        p = i.get("priority", "medium").upper()
        d = i.get("difficulty", "medium")
        deadline = f" ⏰ DEADLINE: {i['deadline']}" if i.get("deadline") else ""
        status_label = f"🚫 Blocked by #{i['blocked_on']}" if i["status"] == "blocked" else "▶️ Ready"
        lines.extend([
            f"### [{p}] #{i['id']} — {i['name']} ({d}){deadline}",
            f"**Status:** {status_label}",
            f"**What:** {i.get('detail', '')}",
            "",
        ])

    if either_items:
        lines.extend([
            "---",
            f"## 🔄 Either — First Available ({len(either_items)} items)",
            "",
        ])
        for i in either_items:
            lines.extend([
                f"### #{i['id']} — {i['name']}",
                f"**What:** {i.get('detail', '')}",
                "",
            ])

    lines.extend([
        "---",
        "## How to use this",
        "",
        "1. Pick a **Desktop** item and start working",
        "2. When you hit a stopping point, save a brain note in `11-Mess Hall/agent-brain/`",
        "3. When something ships, update the queue via: `assigned_to: gentech, status: shipped`",
        "4. If you're blocked by Gentech or Jordan, tag it `blocked` + set `blocked_on`",
        "",
        "---",
        "",
        "*Generated {0} UTC*".format(datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")),
    ])

    content = "\n".join(lines)
    with open(path, "w") as f:
        f.write(content)
    return path, len(forge_items), len(either_items)


def generate_jordan_items(q):
    """Generate Jordan's action items list."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    jordan_items = [
        i for i in q["items"]
        if i.get("assigned_to") == "jordan" and i["status"] == "pending"
    ]

    lines = [
        f"# 👑 Jordan Action Items — {today}",
        "",
    ]
    if jordan_items:
        lines.append(f"## Needs Your Action ({len(jordan_items)} items)")
        lines.append("")
        for i in jordan_items:
            lines.append(f"- **#{i['id']} {i['name']}** — {i.get('detail', '')}")
        lines.append("")

    if not jordan_items:
        lines.append("Nothing pending from you. You're clear! 🎉")

    content = "\n".join(lines)
    path = os.path.join(HANDOFF_DIR, f"{today}-jordan-items.md")
    with open(path, "w") as f:
        f.write(content)
    return path, len(jordan_items)


def summary(q):
    """Print a structured summary — captured by cron, injected into Nightly Build Session."""
    counts = {"pending": 0, "in_progress": 0, "blocked": 0, "completed": 0, "shipped": 0}
    by_agent = {"gentech": 0, "forge": 0, "jordan": 0, "auto": 0}
    by_platform = {"cloud": 0, "desktop": 0, "either": 0, "any": 0}
    urgent = []

    for i in q["items"]:
        s = i["status"]
        if s in counts:
            counts[s] += 1
        a = i.get("assigned_to", "auto")
        if a in by_agent:
            by_agent[a] += 1
        p = i.get("platform", "either")
        if p in by_platform:
            by_platform[p] += 1
        if i.get("priority") == "urgent" and s == "pending":
            urgent.append(i)

    print(f"📋 Build Queue — {len(q['items'])} total items")
    print(f"  ✅ Done: {counts.get('completed', 0) + counts.get('shipped', 0)}")
    print(f"  ⏳ In progress: {counts.get('in_progress', 0)}")
    print(f"  ⏸️  Pending: {counts.get('pending', 0)}")
    print(f"  🚫 Blocked: {counts.get('blocked', 0)}")
    print(f"")
    print(f"👤 By agent: Gentech {by_agent['gentech']} · Forge {by_agent['forge']} · Jordan {by_agent['jordan']} · Auto {by_agent['auto']}")
    print(f"💻 By platform: Cloud {by_platform['cloud']} · Desktop {by_platform['desktop']} · Either {by_platform['either']} · Jordan {by_platform['any']}")
    print(f"")

    if urgent:
        print(f"🚨 URGENT ({len(urgent)}):")
        for i in urgent:
            deadline = f" (due {i.get('deadline', 'soon')})" if i.get('deadline') else ""
            print(f"  #{i['id']} {i['name']}{deadline}")
        print("")

    for agent in ["forge", "gentech"]:
        next_up = find_next_tasks(q, agent, 2)
        if next_up:
            print(f"▶️  Next for {agent.title()}:")
            for t in next_up:
                print(f"  #{t['id']} [{t['difficulty']}/{t['priority']}] {t['name']} ({t.get('platform', 'either')})")
            print("")

    handoff_path, forge_count, either_count = generate_forge_handoff(q)
    print(f"📄 Forge handoff: {handoff_path} ({forge_count} desktop + {either_count} either items)")

    jordan_path, jordan_count = generate_jordan_items(q)
    print(f"👑 Jordan items: {jordan_path} ({jordan_count} pending)")

    print(f"\n✅ Queue tick complete.")


if __name__ == "__main__":
    q = load_queue()
    summary(q)
